# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Eat the Frog

copyright_year: "2019"
company_name: Eat the Frog, LLC

email: brandon.felch@ieatfrog.com
description: >-
  Explore what inspires you.

quote: >-
  Eat a live frog first thing in the morning and nothing worse will happen to you the rest of the day.
author: Mark Twain

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <!-- more -->

social:
    # type: sitename
    # url: https://sitename.com
    # display: false
  -
    type: youtube
    url: https://youtube.com/channel/UCnzrt40jUOSirvUjzfzlpug
  -
    type: twitter
    username: brandonfelch
    url: https://twitter.com/
  -
    type: github
    username: bfelch
    url: https://github.com/

collections:
  activities:
  projects:

defaults:
  -
    scope:
      type: posts
    values:
      permalink: /:categories/:title
  -
    scope:
      path: _posts/activities
    values:
      layout: item
  -
    scope:
      path: _posts/projects
    values:
      layout: item
  -
    scope:
      path: _posts/projects/games
    values:
      categories: projects games
      layout: game

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/