# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KreativDomain
email: felchbrandon@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

quote: >-
  Most good programmers do programming not because they expect to get
  paid or get adulation by the public, but because it is fun to program.
quote_author: Linus Torvalds

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# https://fontawesome.com/icons/youtube-square?style=brands - to get square logo
# http://vectorpaint.yaks.co.nz - to recolor vector, be sure to fit canvas to logo
social:
  -
    type: youtube
    url: https://youtube.com/channel/UC8PTwguNLuEhs0y8dTwC_4Q
    display: false
  -
    type: twitter
    url: https://twitter.com/brandonfelch
  -
    type: github
    url: https://github.com/bfelch
    display: false

collections:
  games:
  #jewelry:
  misc:

defaults:
  -
    scope:
      type: posts
    values:
      permalink: /:categories/:title
  -
    scope:
      path: _posts/projects
    values:
      layout: project
  -
    scope:
      path: _posts/projects/games
    values:
      categories: projects games
      layout: project_game
  -
    scope:
      path: _posts/projects/jewelry
    values:
      categories: projects jewelry
  -
    scope:
      path: _posts/projects/misc
    values:
      categories: projects misc

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
